// 자동 생성 — scripts/i18n/gen_navloc.py 가 scripts/i18n/navloc.json 에서 만든다. 직접 고치지 말 것.

extension NavLoc {
    static let whereToGo = NavLoc(
        ko: "어디로 가시나요?",
        ja: "どこに行きますか？",
        en: "Where to?",
        zh: "想去哪里?",
        zhHant: "想去哪裡?",
        de: "Wohin soll's gehen?",
        es: "¿Adónde vas?",
        fr: "Où allez-vous ?",
        it: "Dove vuoi andare?",
        ptBR: "Para onde você vai?",
        ru: "Куда едем?",
        cs: "Kam to bude?",
        da: "Hvor skal du hen?",
        el: "Πού πηγαίνετε;",
        fi: "Minne mennään?",
        id: "Mau ke mana?",
        nb: "Hvor skal du?",
        nl: "Waar wil je heen?",
        pl: "Dokąd jedziesz?",
        sv: "Vart ska du?",
        th: "จะไปไหนดี?",
        tr: "Nereye gidiyorsun?",
        vi: "Bạn muốn đi đâu?"
    )
    static let tapStationForRoute = NavLoc(
        ko: "역을 탭하면 경로가 보여요",
        ja: "駅をタップして経路を表示",
        en: "Tap a station to see the route",
        zh: "点击车站查看路线",
        zhHant: "點選車站查看路線",
        de: "Tippe auf eine Station, um die Route zu sehen",
        es: "Toca una estación para ver la ruta",
        fr: "Touchez une station pour voir l'itinéraire",
        it: "Tocca una stazione per vedere il percorso",
        ptBR: "Toque em uma estação para ver a rota",
        ru: "Коснитесь станции, чтобы увидеть маршрут",
        cs: "Klepněte na stanici a uvidíte trasu",
        da: "Tryk på en station for at se ruten",
        el: "Πατήστε έναν σταθμό για να δείτε τη διαδρομή",
        fi: "Napauta asemaa nähdäksesi reitin",
        id: "Ketuk stasiun untuk melihat rute",
        nb: "Trykk på en stasjon for å se ruten",
        nl: "Tik op een station om de route te zien",
        pl: "Stuknij stację, by zobaczyć trasę",
        sv: "Tryck på en station för att se rutten",
        th: "แตะสถานีเพื่อดูเส้นทาง",
        tr: "Rotayı görmek için bir istasyona dokun",
        vi: "Chạm vào ga để xem lộ trình"
    )
    static let currentStationTitle = NavLoc(
        ko: "현재 역",
        ja: "現在地",
        en: "Current station",
        zh: "当前车站",
        zhHant: "目前車站",
        de: "Aktuelle Station",
        es: "Estación actual",
        fr: "Station actuelle",
        it: "Stazione attuale",
        ptBR: "Estação atual",
        ru: "Текущая станция",
        cs: "Aktuální stanice",
        da: "Nuværende station",
        el: "Τρέχων σταθμός",
        fi: "Nykyinen asema",
        id: "Stasiun saat ini",
        nb: "Nåværende stasjon",
        nl: "Huidig station",
        pl: "Bieżąca stacja",
        sv: "Nuvarande station",
        th: "สถานีปัจจุบัน",
        tr: "Bulunduğun istasyon",
        vi: "Ga hiện tại"
    )
    static let destinationTitle = NavLoc(
        ko: "목적지",
        ja: "目的地",
        en: "Destination",
        zh: "目的地",
        zhHant: "目的地",
        de: "Ziel",
        es: "Destino",
        fr: "Destination",
        it: "Destinazione",
        ptBR: "Destino",
        ru: "Куда",
        cs: "Cíl",
        da: "Destination",
        el: "Προορισμός",
        fi: "Määränpää",
        id: "Tujuan",
        nb: "Reisemål",
        nl: "Bestemming",
        pl: "Cel",
        sv: "Resmål",
        th: "ปลายทาง",
        tr: "Varış noktası",
        vi: "Điểm đến"
    )
    static let searchPrompt = NavLoc(
        ko: "역 이름",
        ja: "駅名",
        en: "Station name",
        zh: "车站名",
        zhHant: "車站名",
        de: "Stationsname",
        es: "Nombre de la estación",
        fr: "Nom de la station",
        it: "Nome stazione",
        ptBR: "Nome da estação",
        ru: "Название станции",
        cs: "Název stanice",
        da: "Stationsnavn",
        el: "Όνομα σταθμού",
        fi: "Aseman nimi",
        id: "Nama stasiun",
        nb: "Stasjonsnavn",
        nl: "Stationsnaam",
        pl: "Nazwa stacji",
        sv: "Stationsnamn",
        th: "ชื่อสถานี",
        tr: "İstasyon adı",
        vi: "Tên ga"
    )
    static let allLines = NavLoc(
        ko: "전체 노선",
        ja: "全路線",
        en: "All lines",
        zh: "所有线路",
        zhHant: "所有線路",
        de: "Alle Linien",
        es: "Todas las líneas",
        fr: "Toutes les lignes",
        it: "Tutte le linee",
        ptBR: "Todas as linhas",
        ru: "Все линии",
        cs: "Všechny linky",
        da: "Alle linjer",
        el: "Όλες οι γραμμές",
        fi: "Kaikki linjat",
        id: "Semua jalur",
        nb: "Alle linjer",
        nl: "Alle lijnen",
        pl: "Wszystkie linie",
        sv: "Alla linjer",
        th: "ทุกสาย",
        tr: "Tüm hatlar",
        vi: "Tất cả tuyến"
    )
    static let noMatchingStation = NavLoc(
        ko: "일치하는 역이 없어요",
        ja: "該当する駅が見つかりません",
        en: "No matching station",
        zh: "没有找到匹配的车站",
        zhHant: "沒有找到符合的車站",
        de: "Keine passende Station",
        es: "No hay estaciones que coincidan",
        fr: "Aucune station trouvée",
        it: "Nessuna stazione trovata",
        ptBR: "Nenhuma estação encontrada",
        ru: "Станция не найдена",
        cs: "Žádná odpovídající stanice",
        da: "Ingen station fundet",
        el: "Δεν βρέθηκε σταθμός",
        fi: "Asemaa ei löytynyt",
        id: "Stasiun tidak ditemukan",
        nb: "Fant ingen stasjon",
        nl: "Geen station gevonden",
        pl: "Nie znaleziono stacji",
        sv: "Ingen station hittades",
        th: "ไม่พบสถานีที่ตรงกัน",
        tr: "Eşleşen istasyon yok",
        vi: "Không tìm thấy ga phù hợp"
    )
    static let verifyTipTitle = NavLoc(
        ko: "다음 정거장 확인",
        ja: "次の駅を確認",
        en: "Verify the next stop",
        zh: "确认下一站",
        zhHant: "確認下一站",
        de: "Nächste Station prüfen",
        es: "Comprueba la próxima parada",
        fr: "Vérifiez le prochain arrêt",
        it: "Controlla la prossima fermata",
        ptBR: "Confira a próxima estação",
        ru: "Проверьте следующую станцию",
        cs: "Zkontrolujte další stanici",
        da: "Tjek næste station",
        el: "Ελέγξτε την επόμενη στάση",
        fi: "Tarkista seuraava asema",
        id: "Cek stasiun berikutnya",
        nb: "Sjekk neste stasjon",
        nl: "Controleer de volgende halte",
        pl: "Sprawdź następną stację",
        sv: "Kolla nästa station",
        th: "เช็กสถานีถัดไป",
        tr: "Sonraki durağı kontrol et",
        vi: "Kiểm tra ga tiếp theo"
    )
    static let verifyTipMessage = NavLoc(
        ko: "차량 안내판에 이 역명이 나오면 맞는 열차예요. 다른 역이면 내려서 반대편 승강장으로 가세요.",
        ja: "車内の表示にこの駅名が出れば正しい電車です。違う場合は降りて反対側のホームへ。",
        en: "If this station name appears on the in-train display, you're on the right train. If not, get off and take the opposite platform.",
        zh: "如果车内显示这个站名,就是正确的列车。如果不是,请下车前往对面站台。",
        zhHant: "如果車內顯示這個站名,就是正確的列車。如果不是,請下車前往對面月台。",
        de: "Zeigt die Anzeige im Zug diesen Stationsnamen, sitzt du im richtigen Zug. Falls nicht, steig aus und nimm den Zug vom Gegengleis.",
        es: "Si este nombre aparece en la pantalla del vagón, vas en el tren correcto. Si no, bájate y ve al andén de enfrente.",
        fr: "Si ce nom de station s'affiche dans la rame, vous êtes dans le bon train. Sinon, descendez et prenez le quai d'en face.",
        it: "Se questo nome compare sul display del treno, sei sul treno giusto. Altrimenti scendi e prendi il binario opposto.",
        ptBR: "Se este nome aparecer no painel do trem, você está no trem certo. Se não, desça e vá para a plataforma do outro lado.",
        ru: "Если это название появится на табло в вагоне, вы едете правильно. Если нет, выйдите и перейдите на противоположную платформу.",
        cs: "Pokud se tento název objeví na displeji ve voze, jedete správně. Pokud ne, vystupte a přejděte na protější nástupiště.",
        da: "Hvis dette stationsnavn vises på skærmen i toget, sidder du i det rigtige tog. Hvis ikke, så stå af og tag toget fra den modsatte perron.",
        el: "Αν αυτό το όνομα εμφανιστεί στην οθόνη του συρμού, είστε στο σωστό τρένο. Αν όχι, κατεβείτε και πηγαίνετε στην απέναντι αποβάθρα.",
        fi: "Jos tämä aseman nimi näkyy junan näytöllä, olet oikeassa junassa. Jos ei, jää pois ja siirry vastakkaiselle laiturille.",
        id: "Kalau nama stasiun ini muncul di layar kereta, kamu sudah naik kereta yang benar. Kalau tidak, turun lalu pindah ke peron seberang.",
        nb: "Hvis dette stasjonsnavnet vises på skjermen i toget, er du på riktig tog. Hvis ikke, gå av og ta toget fra motsatt plattform.",
        nl: "Staat deze stationsnaam op het scherm in de trein, dan zit je goed. Zo niet, stap uit en neem de trein aan de overkant van het perron.",
        pl: "Jeśli ta nazwa pojawi się na wyświetlaczu w wagonie, jedziesz dobrym pociągiem. Jeśli nie, wysiądź i przejdź na peron po drugiej stronie.",
        sv: "Om det här stationsnamnet visas på skärmen i tåget sitter du på rätt tåg. Om inte, kliv av och ta tåget från motsatta plattformen.",
        th: "ถ้าจอในขบวนแสดงชื่อสถานีนี้ แปลว่าขึ้นถูกขบวนแล้ว ถ้าไม่ใช่ ให้ลงแล้วไปที่ชานชาลาฝั่งตรงข้าม",
        tr: "Bu istasyon adı vagondaki ekranda görünüyorsa doğru trendesin. Görünmüyorsa in ve karşı perondaki trene bin.",
        vi: "Nếu tên ga này hiện trên màn hình trong toa, bạn đã lên đúng tàu. Nếu không, hãy xuống và sang sân ga đối diện."
    )
    static let arrived = NavLoc(
        ko: "도착!",
        ja: "到着!",
        en: "Arrived!",
        zh: "到达!",
        zhHant: "到達!",
        de: "Angekommen!",
        es: "¡Llegaste!",
        fr: "Vous y êtes !",
        it: "Arrivato!",
        ptBR: "Você chegou!",
        ru: "Приехали!",
        cs: "Jste v cíli!",
        da: "Du er fremme!",
        el: "Φτάσατε!",
        fi: "Perillä!",
        id: "Sudah sampai!",
        nb: "Du er fremme!",
        nl: "Je bent er!",
        pl: "Jesteś na miejscu!",
        sv: "Framme!",
        th: "ถึงแล้ว!",
        tr: "Vardın!",
        vi: "Đã đến nơi!"
    )
    static let arrivingSoon = NavLoc(
        ko: "곧 도착",
        ja: "まもなく到着",
        en: "Arriving soon",
        zh: "即将到达",
        zhHant: "即將到達",
        de: "Gleich da",
        es: "Llegando",
        fr: "Arrivée imminente",
        it: "In arrivo",
        ptBR: "Chegando",
        ru: "Скоро прибытие",
        cs: "Za chvíli v cíli",
        da: "Snart fremme",
        el: "Φτάνετε σύντομα",
        fi: "Pian perillä",
        id: "Segera tiba",
        nb: "Snart fremme",
        nl: "Bijna aangekomen",
        pl: "Zaraz dojeżdżamy",
        sv: "Snart framme",
        th: "ใกล้ถึงแล้ว",
        tr: "Varmak üzeresin",
        vi: "Sắp đến"
    )
    static let startOver = NavLoc(
        ko: "다른 곳 찾아가기",
        ja: "別の場所へ行く",
        en: "Find another place",
        zh: "去往其他地方",
        zhHant: "前往其他地方",
        de: "Neues Ziel suchen",
        es: "Ir a otro lugar",
        fr: "Aller ailleurs",
        it: "Vai altrove",
        ptBR: "Ir para outro lugar",
        ru: "Поехать в другое место",
        cs: "Jet jinam",
        da: "Find et andet sted",
        el: "Νέος προορισμός",
        fi: "Uusi määränpää",
        id: "Cari tujuan lain",
        nb: "Finn et annet sted",
        nl: "Ergens anders heen",
        pl: "Jedź gdzie indziej",
        sv: "Åk någon annanstans",
        th: "ไปที่อื่น",
        tr: "Başka yere git",
        vi: "Đi nơi khác"
    )
    static let correctPosition = NavLoc(
        ko: "현재 위치 수정",
        ja: "現在地を修正",
        en: "Correct my position",
        zh: "修正当前位置",
        zhHant: "修正目前位置",
        de: "Position korrigieren",
        es: "Corregir mi posición",
        fr: "Corriger ma position",
        it: "Correggi posizione",
        ptBR: "Corrigir minha posição",
        ru: "Уточнить положение",
        cs: "Opravit polohu",
        da: "Ret min position",
        el: "Διόρθωση θέσης",
        fi: "Korjaa sijaintini",
        id: "Perbaiki posisi saya",
        nb: "Rett posisjonen min",
        nl: "Mijn positie corrigeren",
        pl: "Popraw położenie",
        sv: "Rätta min position",
        th: "แก้ไขตำแหน่งของฉัน",
        tr: "Konumumu düzelt",
        vi: "Sửa vị trí của tôi"
    )
    static let changeDepartureStation = NavLoc(
        ko: "출발역 변경",
        ja: "出発駅を変更",
        en: "Change start",
        zh: "更改出发站",
        zhHant: "更改出發站",
        de: "Start ändern",
        es: "Cambiar origen",
        fr: "Changer le départ",
        it: "Cambia partenza",
        ptBR: "Mudar origem",
        ru: "Сменить старт",
        cs: "Změnit start",
        da: "Skift start",
        el: "Αλλαγή αφετηρίας",
        fi: "Vaihda lähtöasema",
        id: "Ganti asal",
        nb: "Bytt start",
        nl: "Start wijzigen",
        pl: "Zmień start",
        sv: "Byt start",
        th: "เปลี่ยนต้นทาง",
        tr: "Başlangıcı değiştir",
        vi: "Đổi ga đi"
    )
    static let changeLanguageAction = NavLoc(
        ko: "언어 변경",
        ja: "言語を変更",
        en: "Change language",
        zh: "更改语言",
        zhHant: "更改語言",
        de: "Sprache ändern",
        es: "Cambiar idioma",
        fr: "Changer de langue",
        it: "Cambia lingua",
        ptBR: "Mudar idioma",
        ru: "Сменить язык",
        cs: "Změnit jazyk",
        da: "Skift sprog",
        el: "Αλλαγή γλώσσας",
        fi: "Vaihda kieli",
        id: "Ganti bahasa",
        nb: "Bytt språk",
        nl: "Taal wijzigen",
        pl: "Zmień język",
        sv: "Byt språk",
        th: "เปลี่ยนภาษา",
        tr: "Dili değiştir",
        vi: "Đổi ngôn ngữ"
    )
    static let longPressLanguageHint = NavLoc(
        ko: "길게 누르면 언어를 바꿀 수 있어요",
        ja: "長押しで言語を変更できます",
        en: "Long-press to change the language",
        zh: "长按可更改语言",
        zhHant: "長按可更改語言",
        de: "Lange drücken, um die Sprache zu ändern",
        es: "Mantén pulsado para cambiar el idioma",
        fr: "Appui long pour changer de langue",
        it: "Tieni premuto per cambiare lingua",
        ptBR: "Toque e segure para mudar o idioma",
        ru: "Удерживайте, чтобы сменить язык",
        cs: "Podržením změníte jazyk",
        da: "Hold fingeren nede for at skifte sprog",
        el: "Πατήστε παρατεταμένα για αλλαγή γλώσσας",
        fi: "Vaihda kieli pitämällä painettuna",
        id: "Tekan lama untuk mengganti bahasa",
        nb: "Hold inne for å bytte språk",
        nl: "Houd ingedrukt om de taal te wijzigen",
        pl: "Przytrzymaj, by zmienić język",
        sv: "Håll ned för att byta språk",
        th: "กดค้างเพื่อเปลี่ยนภาษา",
        tr: "Dili değiştirmek için basılı tut",
        vi: "Nhấn giữ để đổi ngôn ngữ"
    )
    static let pickCurrentStation = NavLoc(
        ko: "지금 어느 역인가요?",
        ja: "今どの駅にいますか？",
        en: "Which station are you at now?",
        zh: "您现在在哪一站?",
        zhHant: "您現在在哪一站?",
        de: "An welcher Station bist du gerade?",
        es: "¿En qué estación estás?",
        fr: "À quelle station êtes-vous ?",
        it: "In che stazione sei ora?",
        ptBR: "Em que estação você está?",
        ru: "На какой вы станции?",
        cs: "Na které stanici jste?",
        da: "Hvilken station er du på?",
        el: "Σε ποιον σταθμό βρίσκεστε;",
        fi: "Millä asemalla olet nyt?",
        id: "Kamu sekarang di stasiun mana?",
        nb: "Hvilken stasjon er du på nå?",
        nl: "Op welk station ben je nu?",
        pl: "Na jakiej stacji jesteś?",
        sv: "Vilken station är du på nu?",
        th: "ตอนนี้อยู่สถานีไหน?",
        tr: "Şu an hangi istasyondasın?",
        vi: "Bạn đang ở ga nào?"
    )
    static let nextStationShort = NavLoc(
        ko: "다음역",
        ja: "次の駅",
        en: "Next station",
        zh: "下一站",
        zhHant: "下一站",
        de: "Nächste Station",
        es: "Próxima estación",
        fr: "Prochaine station",
        it: "Prossima stazione",
        ptBR: "Próxima estação",
        ru: "Следующая станция",
        cs: "Příští stanice",
        da: "Næste station",
        el: "Επόμενος σταθμός",
        fi: "Seuraava asema",
        id: "Stasiun berikutnya",
        nb: "Neste stasjon",
        nl: "Volgend station",
        pl: "Następna stacja",
        sv: "Nästa station",
        th: "สถานีถัดไป",
        tr: "Sonraki istasyon",
        vi: "Ga tiếp theo"
    )
    static let nearbyStations = NavLoc(
        ko: "가까운 역",
        ja: "近くの駅",
        en: "Nearby stations",
        zh: "附近车站",
        zhHant: "附近車站",
        de: "Stationen in der Nähe",
        es: "Estaciones cercanas",
        fr: "Stations à proximité",
        it: "Stazioni vicine",
        ptBR: "Estações próximas",
        ru: "Станции рядом",
        cs: "Stanice poblíž",
        da: "Stationer i nærheden",
        el: "Κοντινοί σταθμοί",
        fi: "Lähellä olevat asemat",
        id: "Stasiun terdekat",
        nb: "Stasjoner i nærheten",
        nl: "Stations in de buurt",
        pl: "Stacje w pobliżu",
        sv: "Stationer i närheten",
        th: "สถานีใกล้เคียง",
        tr: "Yakındaki istasyonlar",
        vi: "Ga gần đây"
    )
    static let verifyStationNameAlight = NavLoc(
        ko: "역 이름을 확인하고 내리세요",
        ja: "駅名を確認してから降りてください",
        en: "Check the station name before getting off",
        zh: "请确认站名后再下车",
        zhHant: "請確認站名後再下車",
        de: "Vor dem Aussteigen Stationsnamen prüfen",
        es: "Comprueba el nombre de la estación antes de bajar",
        fr: "Vérifiez le nom de la station avant de descendre",
        it: "Controlla il nome della stazione prima di scendere",
        ptBR: "Confira o nome da estação antes de descer",
        ru: "Перед выходом проверьте название станции",
        cs: "Před výstupem zkontrolujte název stanice",
        da: "Tjek stationsnavnet, før du står af",
        el: "Ελέγξτε το όνομα του σταθμού πριν κατεβείτε",
        fi: "Tarkista aseman nimi ennen kuin jäät pois",
        id: "Cek nama stasiun sebelum turun",
        nb: "Sjekk stasjonsnavnet før du går av",
        nl: "Controleer de stationsnaam voor je uitstapt",
        pl: "Przed wyjściem sprawdź nazwę stacji",
        sv: "Kolla stationsnamnet innan du kliver av",
        th: "เช็กชื่อสถานีก่อนลง",
        tr: "İnmeden önce istasyon adını kontrol et",
        vi: "Kiểm tra tên ga trước khi xuống"
    )
    static let alightPositionUnconfirmed = NavLoc(
        ko: "위치 미확정 — 안내방송·역명으로 확인하세요",
        ja: "現在地は推定です — 放送・駅名で確認を",
        en: "Position estimated — verify by sign/announcement",
        zh: "位置为推算 — 请凭广播·站名确认",
        zhHant: "位置為推算 — 請憑廣播·站名確認",
        de: "Position geschätzt — mit Schild/Ansage abgleichen",
        es: "Posición estimada — confírmala con letreros o avisos",
        fr: "Position estimée — vérifiez panneau ou annonce",
        it: "Posizione stimata — verifica cartelli o annunci",
        ptBR: "Posição estimada — confira placa ou aviso",
        ru: "Положение примерное — сверьтесь с табличкой или объявлением",
        cs: "Poloha je odhad — ověřte podle cedule či hlášení",
        da: "Position anslået — tjek skilt eller udkald",
        el: "Εκτιμώμενη θέση — ελέγξτε πινακίδα ή ανακοίνωση",
        fi: "Sijainti arvio — tarkista kyltistä tai kuulutuksesta",
        id: "Posisi perkiraan — cek papan atau pengumuman",
        nb: "Anslått posisjon — sjekk skilt eller annonsering",
        nl: "Positie geschat — check bord of omroep",
        pl: "Położenie szacunkowe — sprawdź tablicę lub komunikat",
        sv: "Uppskattad position — kolla skylt eller utrop",
        th: "ตำแหน่งโดยประมาณ — เช็กจากป้ายหรือประกาศ",
        tr: "Tahmini konum — tabela veya anonsla doğrula",
        vi: "Vị trí ước tính — kiểm tra biển ga hoặc thông báo"
    )
    static let alightPositionConfirmed = NavLoc(
        ko: "위치 확인됨",
        ja: "現在地確認済み",
        en: "Position confirmed",
        zh: "位置已确认",
        zhHant: "位置已確認",
        de: "Position bestätigt",
        es: "Posición confirmada",
        fr: "Position confirmée",
        it: "Posizione confermata",
        ptBR: "Posição confirmada",
        ru: "Положение подтверждено",
        cs: "Poloha potvrzena",
        da: "Position bekræftet",
        el: "Η θέση επιβεβαιώθηκε",
        fi: "Sijainti vahvistettu",
        id: "Posisi terkonfirmasi",
        nb: "Posisjon bekreftet",
        nl: "Positie bevestigd",
        pl: "Położenie potwierdzone",
        sv: "Position bekräftad",
        th: "ยืนยันตำแหน่งแล้ว",
        tr: "Konum doğrulandı",
        vi: "Đã xác nhận vị trí"
    )
    static let positionUncertain = NavLoc(
        ko: "위치가 정확하지 않나요? 탭하여 보정",
        ja: "現在地がずれていますか？タップして修正",
        en: "Position off? Tap to correct",
        zh: "位置不准确？点按修正",
        zhHant: "位置不準確？點選修正",
        de: "Position falsch? Zum Korrigieren tippen",
        es: "¿Posición incorrecta? Toca para corregir",
        fr: "Position erronée ? Touchez pour corriger",
        it: "Posizione errata? Tocca per correggere",
        ptBR: "Posição errada? Toque para corrigir",
        ru: "Неверная станция? Коснитесь, чтобы исправить",
        cs: "Špatná poloha? Klepnutím opravte",
        da: "Forkert position? Tryk for at rette",
        el: "Λάθος θέση; Πατήστε για διόρθωση",
        fi: "Väärä sijainti? Korjaa napauttamalla",
        id: "Posisi salah? Ketuk untuk memperbaiki",
        nb: "Feil posisjon? Trykk for å rette",
        nl: "Positie klopt niet? Tik om te corrigeren",
        pl: "Złe położenie? Stuknij, by poprawić",
        sv: "Fel position? Tryck för att rätta",
        th: "ตำแหน่งไม่ตรง? แตะเพื่อแก้ไข",
        tr: "Konum yanlış mı? Düzeltmek için dokun",
        vi: "Sai vị trí? Chạm để sửa"
    )
    static let approachingNext = NavLoc(
        ko: "다음 역 접근 중",
        ja: "まもなく次の駅",
        en: "Approaching next station",
        zh: "即将到达下一站",
        zhHant: "即將到達下一站",
        de: "Nächste Station in Kürze",
        es: "Llegando a la próxima estación",
        fr: "Arrivée à la prochaine station",
        it: "In arrivo alla prossima stazione",
        ptBR: "Chegando à próxima estação",
        ru: "Подъезжаем к следующей станции",
        cs: "Blížíme se k další stanici",
        da: "Nærmer sig næste station",
        el: "Πλησιάζουμε τον επόμενο σταθμό",
        fi: "Lähestytään seuraavaa asemaa",
        id: "Mendekati stasiun berikutnya",
        nb: "Nærmer seg neste stasjon",
        nl: "Bijna bij het volgende station",
        pl: "Dojeżdżamy do następnej stacji",
        sv: "Närmar sig nästa station",
        th: "กำลังถึงสถานีถัดไป",
        tr: "Sonraki istasyona yaklaşılıyor",
        vi: "Sắp đến ga tiếp theo"
    )
    static let heardFromAnnouncement = NavLoc(
        ko: "안내방송으로 확인됨",
        ja: "車内放送で確認",
        en: "Confirmed by announcement",
        zh: "已通过广播确认",
        zhHant: "已透過廣播確認",
        de: "Per Durchsage bestätigt",
        es: "Confirmado por el aviso",
        fr: "Confirmé par l'annonce",
        it: "Confermato dall'annuncio",
        ptBR: "Confirmado pelo aviso sonoro",
        ru: "Подтверждено объявлением",
        cs: "Potvrzeno hlášením",
        da: "Bekræftet af udkald",
        el: "Επιβεβαιώθηκε από ανακοίνωση",
        fi: "Vahvistettu kuulutuksesta",
        id: "Terkonfirmasi dari pengumuman",
        nb: "Bekreftet av annonsering",
        nl: "Bevestigd door omroep",
        pl: "Potwierdzone komunikatem",
        sv: "Bekräftat av utrop",
        th: "ยืนยันจากเสียงประกาศ",
        tr: "Anonsla doğrulandı",
        vi: "Đã xác nhận qua thông báo"
    )
    static let doorOpensRight = NavLoc(
        ko: "내리실 문: 오른쪽",
        ja: "降り口：右側",
        en: "Doors open: right",
        zh: "下车门：右侧",
        zhHant: "下車門：右側",
        de: "Ausstieg: rechts",
        es: "Puertas: lado derecho",
        fr: "Descente à droite",
        it: "Uscita: lato destro",
        ptBR: "Desembarque pelo lado direito",
        ru: "Выход справа",
        cs: "Výstup vpravo",
        da: "Udstigning: højre side",
        el: "Αποβίβαση από δεξιά",
        fi: "Ovet avautuvat oikealle",
        id: "Pintu keluar: kanan",
        nb: "Avstigning: høyre side",
        nl: "Uitstappen: rechts",
        pl: "Wyjście po prawej",
        sv: "Avstigning: höger sida",
        th: "ประตูเปิดด้านขวา",
        tr: "İniş: sağ taraf",
        vi: "Cửa xuống: bên phải"
    )
    static let doorOpensLeft = NavLoc(
        ko: "내리실 문: 왼쪽",
        ja: "降り口：左側",
        en: "Doors open: left",
        zh: "下车门：左侧",
        zhHant: "下車門：左側",
        de: "Ausstieg: links",
        es: "Puertas: lado izquierdo",
        fr: "Descente à gauche",
        it: "Uscita: lato sinistro",
        ptBR: "Desembarque pelo lado esquerdo",
        ru: "Выход слева",
        cs: "Výstup vlevo",
        da: "Udstigning: venstre side",
        el: "Αποβίβαση από αριστερά",
        fi: "Ovet avautuvat vasemmalle",
        id: "Pintu keluar: kiri",
        nb: "Avstigning: venstre side",
        nl: "Uitstappen: links",
        pl: "Wyjście po lewej",
        sv: "Avstigning: vänster sida",
        th: "ประตูเปิดด้านซ้าย",
        tr: "İniş: sol taraf",
        vi: "Cửa xuống: bên trái"
    )
    static let scanDirectionButton = NavLoc(
        ko: "어느 쪽인지 카메라로 확인",
        ja: "カメラで方向を確認",
        en: "Check direction with camera",
        zh: "用相机确认方向",
        zhHant: "用相機確認方向",
        de: "Richtung mit der Kamera prüfen",
        es: "Comprobar sentido con la cámara",
        fr: "Vérifier le sens avec la caméra",
        it: "Verifica la direzione con la fotocamera",
        ptBR: "Conferir sentido com a câmera",
        ru: "Проверить направление камерой",
        cs: "Ověřit směr fotoaparátem",
        da: "Tjek retningen med kameraet",
        el: "Έλεγχος κατεύθυνσης με την κάμερα",
        fi: "Tarkista suunta kameralla",
        id: "Cek arah dengan kamera",
        nb: "Sjekk retningen med kameraet",
        nl: "Richting checken met camera",
        pl: "Sprawdź kierunek aparatem",
        sv: "Kolla riktningen med kameran",
        th: "เช็กทิศทางด้วยกล้อง",
        tr: "Yönü kamerayla kontrol et",
        vi: "Kiểm tra hướng bằng camera"
    )
    static let scanAimPrompt = NavLoc(
        ko: "열차 행선지(전광판)를 비춰주세요",
        ja: "列車の行先表示を映してください",
        en: "Point at the train's destination display",
        zh: "请对准列车终点站显示屏",
        zhHant: "請對準列車終點站顯示幕",
        de: "Richte die Kamera auf die Zielanzeige des Zugs",
        es: "Apunta al letrero de destino del tren",
        fr: "Visez l'affichage de destination du train",
        it: "Inquadra l'indicatore di destinazione del treno",
        ptBR: "Aponte para o letreiro de destino do trem",
        ru: "Наведите камеру на табло с конечной станцией",
        cs: "Namiřte na směrovou tabuli vlaku",
        da: "Ret kameraet mod togets destinationsskilt",
        el: "Στρέψτε την κάμερα στην ένδειξη προορισμού του τρένου",
        fi: "Suuntaa kamera junan määränpääkylttiin",
        id: "Arahkan kamera ke papan tujuan kereta",
        nb: "Rett kameraet mot togets destinasjonsskilt",
        nl: "Richt op de bestemmingsaanduiding van de trein",
        pl: "Skieruj aparat na tablicę kierunkową pociągu",
        sv: "Rikta kameran mot tågets destinationsskylt",
        th: "ส่องกล้องไปที่ป้ายปลายทางของรถไฟ",
        tr: "Kamerayı trenin gideceği yer tabelasına tut",
        vi: "Hướng camera vào bảng điểm đến của tàu"
    )
    static let scanCorrect = NavLoc(
        ko: "이 방향이 맞아요 — 타세요",
        ja: "この方向で合っています — 乗車OK",
        en: "Correct direction — board here",
        zh: "方向正确 — 可乘车",
        zhHant: "方向正確 — 可搭車",
        de: "Richtige Richtung — einsteigen",
        es: "Sentido correcto — sube",
        fr: "Bon sens — montez",
        it: "Direzione giusta — sali",
        ptBR: "Sentido certo — pode embarcar",
        ru: "Направление верное — садитесь",
        cs: "Správný směr — nastupte",
        da: "Rigtig retning — stig på",
        el: "Σωστή κατεύθυνση — επιβιβαστείτε",
        fi: "Oikea suunta — nouse kyytiin",
        id: "Arah benar — silakan naik",
        nb: "Riktig retning — gå på",
        nl: "Goede richting — instappen",
        pl: "Dobry kierunek — wsiadaj",
        sv: "Rätt riktning — kliv på",
        th: "ทิศทางถูกต้อง — ขึ้นได้เลย",
        tr: "Doğru yön — binebilirsin",
        vi: "Đúng hướng — lên tàu"
    )
    static let scanWrong = NavLoc(
        ko: "반대 방향이에요 — 타지 마세요",
        ja: "逆方向です — 乗らないで",
        en: "Wrong direction — don't board",
        zh: "方向相反 — 请勿乘车",
        zhHant: "方向相反 — 請勿搭車",
        de: "Falsche Richtung — nicht einsteigen",
        es: "Sentido contrario — no subas",
        fr: "Mauvais sens — ne montez pas",
        it: "Direzione sbagliata — non salire",
        ptBR: "Sentido errado — não embarque",
        ru: "Не то направление — не садитесь",
        cs: "Opačný směr — nenastupujte",
        da: "Forkert retning — stig ikke på",
        el: "Λάθος κατεύθυνση — μην επιβιβαστείτε",
        fi: "Väärä suunta — älä nouse",
        id: "Arah salah — jangan naik",
        nb: "Feil retning — ikke gå på",
        nl: "Verkeerde richting — niet instappen",
        pl: "Zły kierunek — nie wsiadaj",
        sv: "Fel riktning — kliv inte på",
        th: "ผิดทิศทาง — อย่าขึ้น",
        tr: "Ters yön — binme",
        vi: "Ngược hướng — đừng lên"
    )
    static let scanSearching = NavLoc(
        ko: "행선지를 찾는 중…",
        ja: "行先を探しています…",
        en: "Looking for a destination sign…",
        zh: "正在识别目的地…",
        zhHant: "正在辨識目的地…",
        de: "Suche nach Zielanzeige …",
        es: "Buscando el destino…",
        fr: "Recherche de la destination…",
        it: "Cerco la destinazione…",
        ptBR: "Procurando o destino…",
        ru: "Ищем табло направления…",
        cs: "Hledám směrovou tabuli…",
        da: "Leder efter destinationsskilt…",
        el: "Αναζήτηση ένδειξης προορισμού…",
        fi: "Etsitään määränpääkylttiä…",
        id: "Mencari papan tujuan…",
        nb: "Ser etter destinasjonsskilt…",
        nl: "Bestemming zoeken…",
        pl: "Szukam tablicy kierunkowej…",
        sv: "Letar efter destinationsskylt…",
        th: "กำลังหาป้ายปลายทาง…",
        tr: "Yön tabelası aranıyor…",
        vi: "Đang tìm bảng điểm đến…"
    )
    static let scanNoCamera = NavLoc(
        ko: "카메라 권한이 필요해요",
        ja: "カメラの許可が必要です",
        en: "Camera permission needed",
        zh: "需要相机权限",
        zhHant: "需要相機權限",
        de: "Kamerazugriff erforderlich",
        es: "Se necesita acceso a la cámara",
        fr: "Accès à la caméra requis",
        it: "Serve l'accesso alla fotocamera",
        ptBR: "É preciso permitir a câmera",
        ru: "Нужен доступ к камере",
        cs: "Je potřeba přístup k fotoaparátu",
        da: "Kræver adgang til kameraet",
        el: "Απαιτείται πρόσβαση στην κάμερα",
        fi: "Kameran käyttöoikeus tarvitaan",
        id: "Perlu izin kamera",
        nb: "Krever tilgang til kameraet",
        nl: "Cameratoegang nodig",
        pl: "Potrzebny dostęp do aparatu",
        sv: "Kameraåtkomst krävs",
        th: "ต้องอนุญาตให้ใช้กล้อง",
        tr: "Kamera izni gerekli",
        vi: "Cần quyền truy cập camera"
    )
    static let gpsSuggestion = NavLoc(
        ko: "위치 기반 추천",
        ja: "位置情報からの候補",
        en: "Location-based guess",
        zh: "根据位置推荐",
        zhHant: "根據位置推薦",
        de: "Vorschlag nach Standort",
        es: "Sugerencia por ubicación",
        fr: "Suggestion selon la position",
        it: "Suggerita dalla posizione",
        ptBR: "Sugestão pela localização",
        ru: "По геопозиции",
        cs: "Návrh podle polohy",
        da: "Forslag ud fra lokalitet",
        el: "Πρόταση βάσει τοποθεσίας",
        fi: "Ehdotus sijainnin mukaan",
        id: "Saran dari lokasi",
        nb: "Forslag ut fra posisjon",
        nl: "Voorstel op basis van locatie",
        pl: "Propozycja z lokalizacji",
        sv: "Förslag utifrån plats",
        th: "แนะนำตามตำแหน่ง",
        tr: "Konuma göre öneri",
        vi: "Gợi ý theo vị trí"
    )
    static let searchingLocation = NavLoc(
        ko: "현재 위치 확인 중...",
        ja: "現在地を取得中...",
        en: "Locating you...",
        zh: "正在定位...",
        zhHant: "正在定位...",
        de: "Standort wird ermittelt …",
        es: "Obteniendo ubicación…",
        fr: "Localisation en cours…",
        it: "Rilevamento posizione…",
        ptBR: "Obtendo localização…",
        ru: "Определяем местоположение…",
        cs: "Zjišťuji polohu…",
        da: "Finder din lokalitet…",
        el: "Εντοπισμός τοποθεσίας…",
        fi: "Haetaan sijaintia…",
        id: "Mencari lokasi…",
        nb: "Finner posisjonen din…",
        nl: "Locatie bepalen…",
        pl: "Ustalanie lokalizacji…",
        sv: "Hämtar din plats…",
        th: "กำลังหาตำแหน่ง…",
        tr: "Konum bulunuyor…",
        vi: "Đang xác định vị trí…"
    )
    static let stopsToAlight = NavLoc(
        ko: "내릴 곳까지",
        ja: "降車駅まで",
        en: "Until you get off",
        zh: "到下车站",
        zhHant: "到下車站",
        de: "Bis zum Aussteigen",
        es: "Hasta bajar",
        fr: "Avant de descendre",
        it: "Alla tua fermata",
        ptBR: "Até descer",
        ru: "До выхода",
        cs: "Do výstupu",
        da: "Til du skal af",
        el: "Μέχρι την αποβίβαση",
        fi: "Poisjääntiin",
        id: "Sampai turun",
        nb: "Til du skal av",
        nl: "Tot uitstappen",
        pl: "Do wyjścia",
        sv: "Tills du ska av",
        th: "ก่อนถึงสถานีที่ต้องลง",
        tr: "İneceğin yere",
        vi: "Đến ga xuống"
    )
    static let etaLabel = NavLoc(
        ko: "도착 예정",
        ja: "到着予定",
        en: "ETA",
        zh: "预计到达",
        zhHant: "預計到達",
        de: "Ankunft",
        es: "Llegada",
        fr: "Arrivée prévue",
        it: "Arrivo previsto",
        ptBR: "Chegada prevista",
        ru: "Прибытие",
        cs: "Příjezd",
        da: "Ankomst",
        el: "Άφιξη",
        fi: "Arvioitu saapuminen",
        id: "Perkiraan tiba",
        nb: "Ankomst",
        nl: "Aankomst",
        pl: "Przyjazd",
        sv: "Ankomst",
        th: "ถึงประมาณ",
        tr: "Tahmini varış",
        vi: "Dự kiến đến"
    )
    static let alightCalm = NavLoc(
        ko: "내릴 역",
        ja: "降車駅",
        en: "Get off at",
        zh: "下车站",
        zhHant: "下車站",
        de: "Aussteigen an",
        es: "Bajar en",
        fr: "Descendre à",
        it: "Scendi a",
        ptBR: "Desça em",
        ru: "Выход на станции",
        cs: "Výstup ve stanici",
        da: "Stå af ved",
        el: "Αποβίβαση στο",
        fi: "Jää pois asemalla",
        id: "Turun di",
        nb: "Gå av på",
        nl: "Uitstappen bij",
        pl: "Stacja docelowa",
        sv: "Kliv av vid",
        th: "ลงที่",
        tr: "İneceğin istasyon",
        vi: "Xuống tại"
    )
    static let prepareToGetOff = NavLoc(
        ko: "곧 내릴 준비하세요",
        ja: "そろそろ降車の準備",
        en: "Prepare to get off",
        zh: "请准备下车",
        zhHant: "請準備下車",
        de: "Bald aussteigen",
        es: "Prepárate para bajar",
        fr: "Préparez-vous à descendre",
        it: "Preparati a scendere",
        ptBR: "Prepare-se para descer",
        ru: "Готовьтесь к выходу",
        cs: "Připravte se k výstupu",
        da: "Gør dig klar til at stå af",
        el: "Ετοιμαστείτε να κατεβείτε",
        fi: "Valmistaudu jäämään pois",
        id: "Bersiap turun",
        nb: "Gjør deg klar til å gå av",
        nl: "Maak je klaar om uit te stappen",
        pl: "Przygotuj się do wyjścia",
        sv: "Gör dig redo att kliva av",
        th: "เตรียมตัวลง",
        tr: "İnmeye hazırlan",
        vi: "Chuẩn bị xuống tàu"
    )
    static let nextStopGetOff = NavLoc(
        ko: "다음 정거장에서 내리세요",
        ja: "次の駅で降りてください",
        en: "Get off at the next stop",
        zh: "请在下一站下车",
        zhHant: "請在下一站下車",
        de: "An der nächsten Station aussteigen",
        es: "Baja en la próxima parada",
        fr: "Descendez au prochain arrêt",
        it: "Scendi alla prossima fermata",
        ptBR: "Desça na próxima estação",
        ru: "Выходите на следующей",
        cs: "Vystupte na příští stanici",
        da: "Stå af ved næste station",
        el: "Κατεβείτε στην επόμενη στάση",
        fi: "Jää pois seuraavalla asemalla",
        id: "Turun di stasiun berikutnya",
        nb: "Gå av på neste stasjon",
        nl: "Stap uit bij de volgende halte",
        pl: "Wysiądź na następnej stacji",
        sv: "Kliv av vid nästa station",
        th: "ลงสถานีถัดไป",
        tr: "Sonraki istasyonda in",
        vi: "Xuống ở ga tiếp theo"
    )
    static let getOffNow = NavLoc(
        ko: "지금 내리세요!",
        ja: "今降りてください!",
        en: "Get off now!",
        zh: "请立即下车!",
        zhHant: "請立即下車!",
        de: "Jetzt aussteigen!",
        es: "¡Baja ahora!",
        fr: "Descendez maintenant !",
        it: "Scendi ora!",
        ptBR: "Desça agora!",
        ru: "Выходите сейчас!",
        cs: "Vystupte teď!",
        da: "Stå af nu!",
        el: "Κατεβείτε τώρα!",
        fi: "Jää pois nyt!",
        id: "Turun sekarang!",
        nb: "Gå av nå!",
        nl: "Nu uitstappen!",
        pl: "Wysiądź teraz!",
        sv: "Kliv av nu!",
        th: "ลงเดี๋ยวนี้!",
        tr: "Şimdi in!",
        vi: "Xuống ngay!"
    )
    static let noRouteFound = NavLoc(
        ko: "경로를 찾을 수 없어요",
        ja: "経路が見つかりません",
        en: "No route found",
        zh: "找不到路线",
        zhHant: "找不到路線",
        de: "Keine Route gefunden",
        es: "No se encontró ruta",
        fr: "Aucun itinéraire trouvé",
        it: "Nessun percorso trovato",
        ptBR: "Nenhuma rota encontrada",
        ru: "Маршрут не найден",
        cs: "Trasa nenalezena",
        da: "Ingen rute fundet",
        el: "Δεν βρέθηκε διαδρομή",
        fi: "Reittiä ei löytynyt",
        id: "Rute tidak ditemukan",
        nb: "Fant ingen rute",
        nl: "Geen route gevonden",
        pl: "Nie znaleziono trasy",
        sv: "Ingen rutt hittades",
        th: "ไม่พบเส้นทาง",
        tr: "Rota bulunamadı",
        vi: "Không tìm thấy lộ trình"
    )
    static let noRouteHint = NavLoc(
        ko: "최대 2회 환승으로 도달할 수 있는 경로가 없어요",
        ja: "最大2回までの乗換で到達できる経路がありません",
        en: "No route reachable within two transfers",
        zh: "两次换乘内无法到达",
        zhHant: "兩次轉乘內無法到達",
        de: "Mit höchstens zwei Umstiegen nicht erreichbar",
        es: "No hay ruta con dos transbordos como máximo",
        fr: "Aucun itinéraire avec deux correspondances maximum",
        it: "Nessun percorso con al massimo due cambi",
        ptBR: "Não há rota com até duas baldeações",
        ru: "Нет маршрута максимум с двумя пересадками",
        cs: "Neexistuje trasa s nejvýše dvěma přestupy",
        da: "Ingen rute med højst to skift",
        el: "Καμία διαδρομή με έως δύο μετεπιβιβάσεις",
        fi: "Reittiä ei löydy enintään kahdella vaihdolla",
        id: "Tidak ada rute dengan maksimal dua kali transit",
        nb: "Ingen rute med maks to bytter",
        nl: "Geen route met maximaal twee overstappen",
        pl: "Brak trasy z maksymalnie dwiema przesiadkami",
        sv: "Ingen rutt med högst två byten",
        th: "ไม่มีเส้นทางที่ต่อรถไม่เกินสองครั้ง",
        tr: "En fazla iki aktarmayla gidilebilen rota yok",
        vi: "Không có lộ trình nào với tối đa hai lần chuyển tuyến"
    )
    static let pickAnotherDestination = NavLoc(
        ko: "다른 목적지 선택",
        ja: "別の目的地を選ぶ",
        en: "Pick a different destination",
        zh: "选择其他目的地",
        zhHant: "選擇其他目的地",
        de: "Anderes Ziel wählen",
        es: "Elegir otro destino",
        fr: "Choisir une autre destination",
        it: "Scegli un'altra destinazione",
        ptBR: "Escolher outro destino",
        ru: "Выбрать другую станцию",
        cs: "Vybrat jiný cíl",
        da: "Vælg en anden destination",
        el: "Επιλογή άλλου προορισμού",
        fi: "Valitse toinen määränpää",
        id: "Pilih tujuan lain",
        nb: "Velg et annet reisemål",
        nl: "Kies een andere bestemming",
        pl: "Wybierz inny cel",
        sv: "Välj ett annat resmål",
        th: "เลือกปลายทางอื่น",
        tr: "Başka bir yer seç",
        vi: "Chọn điểm đến khác"
    )
    static let languagePickerTitle = NavLoc(
        ko: "언어",
        ja: "言語",
        en: "Language",
        zh: "语言",
        zhHant: "語言",
        de: "Sprache",
        es: "Idioma",
        fr: "Langue",
        it: "Lingua",
        ptBR: "Idioma",
        ru: "Язык",
        cs: "Jazyk",
        da: "Sprog",
        el: "Γλώσσα",
        fi: "Kieli",
        id: "Bahasa",
        nb: "Språk",
        nl: "Taal",
        pl: "Język",
        sv: "Språk",
        th: "ภาษา",
        tr: "Dil",
        vi: "Ngôn ngữ"
    )
    static let done = NavLoc(
        ko: "완료",
        ja: "完了",
        en: "Done",
        zh: "完成",
        zhHant: "完成",
        de: "Fertig",
        es: "OK",
        fr: "OK",
        it: "Fine",
        ptBR: "OK",
        ru: "Готово",
        cs: "Hotovo",
        da: "OK",
        el: "Τέλος",
        fi: "Valmis",
        id: "Selesai",
        nb: "Ferdig",
        nl: "Gereed",
        pl: "Gotowe",
        sv: "Klar",
        th: "เสร็จสิ้น",
        tr: "Bitti",
        vi: "Xong"
    )
    static let autoLabel = NavLoc(
        ko: "자동",
        ja: "自動",
        en: "Auto",
        zh: "自动",
        zhHant: "自動",
        de: "Automatisch",
        es: "Automático",
        fr: "Automatique",
        it: "Automatica",
        ptBR: "Automático",
        ru: "Автоматически",
        cs: "Automaticky",
        da: "Automatisk",
        el: "Αυτόματα",
        fi: "Automaattinen",
        id: "Otomatis",
        nb: "Automatisk",
        nl: "Automatisch",
        pl: "Automatycznie",
        sv: "Automatiskt",
        th: "อัตโนมัติ",
        tr: "Otomatik",
        vi: "Tự động"
    )
    static let contactSectionTitle = NavLoc(
        ko: "개발자에게 문의",
        ja: "開発者へのお問い合わせ",
        en: "Contact the Developer",
        zh: "联系开发者",
        zhHant: "聯絡開發者",
        de: "Entwickler kontaktieren",
        es: "Contactar al desarrollador",
        fr: "Contacter le développeur",
        it: "Contatta lo sviluppatore",
        ptBR: "Fale com o desenvolvedor",
        ru: "Связаться с разработчиком",
        cs: "Kontaktovat vývojáře",
        da: "Kontakt udvikleren",
        el: "Επικοινωνία με τον προγραμματιστή",
        fi: "Ota yhteyttä kehittäjään",
        id: "Hubungi Pengembang",
        nb: "Kontakt utvikleren",
        nl: "Contact met de ontwikkelaar",
        pl: "Kontakt z twórcą",
        sv: "Kontakta utvecklaren",
        th: "ติดต่อผู้พัฒนา",
        tr: "Geliştiriciyle iletişim",
        vi: "Liên hệ nhà phát triển"
    )
    static let contactEmail = NavLoc(
        ko: "이메일로 문의하기",
        ja: "メールで問い合わせる",
        en: "Email",
        zh: "通过邮件联系",
        zhHant: "透過電子郵件聯絡",
        de: "Per E-Mail schreiben",
        es: "Escribir un correo",
        fr: "Écrire un e-mail",
        it: "Scrivi un'e-mail",
        ptBR: "Enviar e-mail",
        ru: "Написать на почту",
        cs: "Napsat e-mail",
        da: "Skriv en e-mail",
        el: "Αποστολή email",
        fi: "Lähetä sähköpostia",
        id: "Kirim email",
        nb: "Send e-post",
        nl: "Stuur een e-mail",
        pl: "Napisz e-mail",
        sv: "Skicka mejl",
        th: "ส่งอีเมล",
        tr: "E-posta gönder",
        vi: "Gửi email"
    )
    static let contactInstagram = NavLoc(
        ko: "인스타그램 DM (@lee25_ios)",
        ja: "インスタグラムDM (@lee25_ios)",
        en: "Instagram DM (@lee25_ios)",
        zh: "Instagram 私信 (@lee25_ios)",
        zhHant: "Instagram 私訊 (@lee25_ios)",
        de: "Instagram-DM (@lee25_ios)",
        es: "Mensaje por Instagram (@lee25_ios)",
        fr: "Message Instagram (@lee25_ios)",
        it: "DM su Instagram (@lee25_ios)",
        ptBR: "Direct no Instagram (@lee25_ios)",
        ru: "Сообщение в Instagram (@lee25_ios)",
        cs: "Zpráva na Instagramu (@lee25_ios)",
        da: "Besked på Instagram (@lee25_ios)",
        el: "Μήνυμα στο Instagram (@lee25_ios)",
        fi: "Viesti Instagramissa (@lee25_ios)",
        id: "DM Instagram (@lee25_ios)",
        nb: "Melding på Instagram (@lee25_ios)",
        nl: "Instagram-DM (@lee25_ios)",
        pl: "Wiadomość na Instagramie (@lee25_ios)",
        sv: "Meddelande på Instagram (@lee25_ios)",
        th: "DM ทาง Instagram (@lee25_ios)",
        tr: "Instagram DM (@lee25_ios)",
        vi: "Nhắn tin Instagram (@lee25_ios)"
    )
    static let contactFooter = NavLoc(
        ko: "버그 제보와 기능 제안을 환영합니다.",
        ja: "バグ報告や機能のご提案を歓迎します。",
        en: "Bug reports and feature suggestions are welcome.",
        zh: "欢迎反馈问题和提出功能建议。",
        zhHant: "歡迎回報問題並提出功能建議。",
        de: "Fehlermeldungen und Ideen sind jederzeit willkommen.",
        es: "Agradecemos los reportes de errores y las sugerencias.",
        fr: "Signalements de bugs et suggestions bienvenus.",
        it: "Segnalazioni di bug e suggerimenti sono benvenuti.",
        ptBR: "Relatos de bugs e sugestões são muito bem-vindos.",
        ru: "Будем рады сообщениям об ошибках и идеям.",
        cs: "Hlášení chyb i nápady jsou vítány.",
        da: "Fejlrapporter og idéer er meget velkomne.",
        el: "Αναφορές σφαλμάτων και ιδέες είναι ευπρόσδεκτες.",
        fi: "Virheilmoitukset ja ideat ovat tervetulleita.",
        id: "Laporan bug dan saran fitur sangat kami hargai.",
        nb: "Feilrapporter og forslag er hjertelig velkomne.",
        nl: "Bugmeldingen en ideeën zijn van harte welkom.",
        pl: "Zgłoszenia błędów i pomysły są mile widziane.",
        sv: "Felrapporter och idéer är varmt välkomna.",
        th: "ยินดีรับแจ้งปัญหาและข้อเสนอแนะเสมอ",
        tr: "Hata bildirimleri ve öneriler her zaman memnuniyetle karşılanır.",
        vi: "Rất hoan nghênh báo lỗi và góp ý tính năng."
    )
    static let locationErrorNoStation = NavLoc(
        ko: "근처에서 역을 찾을 수 없어요",
        ja: "近くに駅が見つかりませんでした",
        en: "No nearby station found",
        zh: "附近找不到车站",
        zhHant: "附近找不到車站",
        de: "Keine Station in der Nähe gefunden",
        es: "No hay estaciones cerca",
        fr: "Aucune station à proximité",
        it: "Nessuna stazione nelle vicinanze",
        ptBR: "Nenhuma estação por perto",
        ru: "Поблизости нет станций",
        cs: "Poblíž není žádná stanice",
        da: "Ingen station i nærheden",
        el: "Δεν βρέθηκε κοντινός σταθμός",
        fi: "Lähistöltä ei löytynyt asemaa",
        id: "Tidak ada stasiun di dekat sini",
        nb: "Fant ingen stasjon i nærheten",
        nl: "Geen station in de buurt gevonden",
        pl: "Brak stacji w pobliżu",
        sv: "Ingen station i närheten",
        th: "ไม่พบสถานีใกล้เคียง",
        tr: "Yakında istasyon bulunamadı",
        vi: "Không tìm thấy ga nào gần đây"
    )
    static let locationErrorFetchFailed = NavLoc(
        ko: "현재 위치를 가져오지 못했어요",
        ja: "現在地の取得に失敗しました",
        en: "Couldn't get your location",
        zh: "无法获取当前位置",
        zhHant: "無法取得目前位置",
        de: "Standort konnte nicht ermittelt werden",
        es: "No se pudo obtener tu ubicación",
        fr: "Impossible d'obtenir votre position",
        it: "Impossibile rilevare la posizione",
        ptBR: "Não foi possível obter sua localização",
        ru: "Не удалось определить местоположение",
        cs: "Polohu se nepodařilo zjistit",
        da: "Kunne ikke finde din lokalitet",
        el: "Δεν ήταν δυνατός ο εντοπισμός της τοποθεσίας",
        fi: "Sijaintia ei saatu haettua",
        id: "Lokasi tidak dapat ditemukan",
        nb: "Kunne ikke finne posisjonen din",
        nl: "Kan je locatie niet bepalen",
        pl: "Nie udało się ustalić lokalizacji",
        sv: "Det gick inte att hämta din plats",
        th: "ไม่สามารถหาตำแหน่งของคุณได้",
        tr: "Konumun alınamadı",
        vi: "Không thể lấy vị trí của bạn"
    )
    static let locationErrorDenied = NavLoc(
        ko: "위치 권한이 꺼져 있어요 (설정 → 한국 길찾기 → 위치)",
        ja: "位置情報の権限が許可されていません（設定 → 韓国ナビ → 位置情報）",
        en: "Location access is off (Settings → Korea Wayfinder → Location)",
        zh: "未开启定位权限（设置 → 韩国导航 → 位置）",
        zhHant: "未開啟定位權限（設定 → 韓國導航 → 位置）",
        de: "Standortzugriff ist aus (Einstellungen → Korea-Wegweiser → Standort)",
        es: "El acceso a la ubicación está desactivado (Ajustes → Guía Corea → Ubicación)",
        fr: "Accès à la position désactivé (Réglages → Guide Corée → Position)",
        it: "L'accesso alla posizione è disattivato (Impostazioni → Guida Corea → Posizione)",
        ptBR: "O acesso à localização está desativado (Ajustes → Guia Coreia → Localização)",
        ru: "Доступ к геопозиции выключен (Настройки → Навигатор Корея → Геопозиция)",
        cs: "Přístup k poloze je vypnutý (Nastavení → Průvodce Koreou → Poloha)",
        da: "Adgang til lokalitet er slået fra (Indstillinger → Koreaguide → Lokalitet)",
        el: "Η πρόσβαση στην τοποθεσία είναι απενεργοποιημένη (Ρυθμίσεις → Οδηγός Κορέας → Τοποθεσία)",
        fi: "Sijainnin käyttö on pois päältä (Asetukset → Korea-opas → Sijainti)",
        id: "Akses lokasi nonaktif (Pengaturan → Navigasi Korea → Lokasi)",
        nb: "Tilgang til posisjon er av (Innstillinger → Koreaguide → Posisjon)",
        nl: "Locatietoegang staat uit (Instellingen → Korea Wegwijzer → Locatie)",
        pl: "Dostęp do lokalizacji jest wyłączony (Ustawienia → Nawigator Korea → Lokalizacja)",
        sv: "Platsåtkomst är avstängd (Inställningar → Koreaguiden → Plats)",
        th: "ปิดการเข้าถึงตำแหน่งอยู่ (การตั้งค่า → นำทางเกาหลี → ตำแหน่งที่ตั้ง)",
        tr: "Konum erişimi kapalı (Ayarlar → Kore Rehberi → Konum)",
        vi: "Quyền truy cập vị trí đang tắt (Cài đặt → Metro Hàn Quốc → Vị trí)"
    )
    static let locationErrorUnavailable = NavLoc(
        ko: "현재 위치를 가져오지 못했어요. 출발역을 직접 골라주세요",
        ja: "現在地を取得できませんでした。出発駅を手動で選んでください",
        en: "Couldn't get your location. Please pick your starting station",
        zh: "无法获取当前位置，请手动选择出发车站",
        zhHant: "無法取得目前位置，請手動選擇出發車站",
        de: "Standort konnte nicht ermittelt werden. Bitte wähle deine Startstation selbst.",
        es: "No se pudo obtener tu ubicación. Elige tu estación de salida.",
        fr: "Impossible d'obtenir votre position. Choisissez votre station de départ.",
        it: "Impossibile rilevare la posizione. Scegli tu la stazione di partenza.",
        ptBR: "Não foi possível obter sua localização. Escolha a estação de partida.",
        ru: "Не удалось определить местоположение. Выберите станцию отправления вручную.",
        cs: "Polohu se nepodařilo zjistit. Vyberte výchozí stanici ručně.",
        da: "Kunne ikke finde din lokalitet. Vælg selv din startstation.",
        el: "Δεν ήταν δυνατός ο εντοπισμός της τοποθεσίας. Επιλέξτε μόνοι σας τον σταθμό αφετηρίας.",
        fi: "Sijaintia ei saatu haettua. Valitse lähtöasema itse.",
        id: "Lokasi tidak dapat ditemukan. Silakan pilih stasiun keberangkatan sendiri.",
        nb: "Kunne ikke finne posisjonen din. Velg startstasjon selv.",
        nl: "Kan je locatie niet bepalen. Kies zelf je vertrekstation.",
        pl: "Nie udało się ustalić lokalizacji. Wybierz stację początkową samodzielnie.",
        sv: "Det gick inte att hämta din plats. Välj startstation själv.",
        th: "ไม่สามารถหาตำแหน่งของคุณได้ โปรดเลือกสถานีต้นทางเอง",
        tr: "Konumun alınamadı. Lütfen başlangıç istasyonunu kendin seç.",
        vi: "Không thể lấy vị trí của bạn. Hãy tự chọn ga xuất phát."
    )
    static let locationErrorTimeout = NavLoc(
        ko: "위치를 가져오는 데 시간이 너무 오래 걸려요",
        ja: "位置情報の取得がタイムアウトしました",
        en: "Getting your location timed out",
        zh: "获取位置超时",
        zhHant: "取得位置逾時",
        de: "Die Standortermittlung hat zu lange gedauert",
        es: "Obtener la ubicación tardó demasiado",
        fr: "La localisation a pris trop de temps",
        it: "Il rilevamento della posizione ha richiesto troppo tempo",
        ptBR: "A localização demorou demais",
        ru: "Определение местоположения заняло слишком много времени",
        cs: "Zjišťování polohy trvalo příliš dlouho",
        da: "Det tog for lang tid at finde din lokalitet",
        el: "Ο εντοπισμός τοποθεσίας άργησε πολύ",
        fi: "Sijainnin haku kesti liian kauan",
        id: "Pencarian lokasi terlalu lama",
        nb: "Det tok for lang tid å finne posisjonen",
        nl: "Locatie bepalen duurde te lang",
        pl: "Ustalanie lokalizacji trwało zbyt długo",
        sv: "Det tog för lång tid att hämta din plats",
        th: "การหาตำแหน่งใช้เวลานานเกินไป",
        tr: "Konum alma çok uzun sürdü",
        vi: "Lấy vị trí mất quá nhiều thời gian"
    )
    static let stopsUnit = NavLoc(
        ko: "정거장",
        ja: "駅",
        en: "stops",
        zh: "站",
        zhHant: "站",
        de: "Stationen",
        es: "paradas",
        fr: "arrêts",
        it: "fermate",
        ptBR: "estações",
        ru: "станций",
        cs: "stanic",
        da: "stationer",
        el: "στάσεις",
        fi: "asemaa",
        id: "stasiun",
        nb: "stasjoner",
        nl: "haltes",
        pl: "stacji",
        sv: "stationer",
        th: "สถานี",
        tr: "durak",
        vi: "ga"
    )
    static let tipTitle = NavLoc(
        ko: "언어 전환",
        ja: "言語の切り替え",
        en: "Switch language",
        zh: "切换语言",
        zhHant: "切換語言",
        de: "Sprache wechseln",
        es: "Cambiar idioma",
        fr: "Changer de langue",
        it: "Cambia lingua",
        ptBR: "Mudar idioma",
        ru: "Смена языка",
        cs: "Změna jazyka",
        da: "Skift sprog",
        el: "Αλλαγή γλώσσας",
        fi: "Kielen vaihto",
        id: "Ganti bahasa",
        nb: "Bytt språk",
        nl: "Taal wisselen",
        pl: "Zmiana języka",
        sv: "Byt språk",
        th: "เปลี่ยนภาษา",
        tr: "Dil değiştir",
        vi: "Đổi ngôn ngữ"
    )
    static let tipMessage = NavLoc(
        ko: "역 이름을 길게 누르면 표시 언어를 바꿀 수 있어요.",
        ja: "駅名を長押しすると、表示言語を変更できます。",
        en: "Long-press a station name to change the display language.",
        zh: "长按车站名可更改显示语言。",
        zhHant: "長按車站名可更改顯示語言。",
        de: "Halte einen Stationsnamen gedrückt, um die Anzeigesprache zu ändern.",
        es: "Mantén pulsado el nombre de una estación para cambiar el idioma.",
        fr: "Maintenez le doigt sur un nom de station pour changer la langue d'affichage.",
        it: "Tieni premuto il nome di una stazione per cambiare la lingua.",
        ptBR: "Toque e segure o nome de uma estação para mudar o idioma.",
        ru: "Удерживайте название станции, чтобы сменить язык интерфейса.",
        cs: "Podržením názvu stanice změníte jazyk aplikace.",
        da: "Hold fingeren på et stationsnavn for at skifte visningssprog.",
        el: "Πατήστε παρατεταμένα ένα όνομα σταθμού για να αλλάξετε τη γλώσσα.",
        fi: "Vaihda näyttökieli pitämällä aseman nimeä painettuna.",
        id: "Tekan lama nama stasiun untuk mengganti bahasa tampilan.",
        nb: "Hold inne et stasjonsnavn for å bytte visningsspråk.",
        nl: "Houd een stationsnaam ingedrukt om de weergavetaal te wijzigen.",
        pl: "Przytrzymaj nazwę stacji, by zmienić język aplikacji.",
        sv: "Håll ned ett stationsnamn för att byta visningsspråk.",
        th: "กดชื่อสถานีค้างไว้เพื่อเปลี่ยนภาษาที่แสดง",
        tr: "Görüntüleme dilini değiştirmek için bir istasyon adına basılı tut.",
        vi: "Nhấn giữ tên ga để đổi ngôn ngữ hiển thị."
    )
    static let a11yNextStop = NavLoc(
        ko: "{0}역 출발, 다음 정거장 {1}역",
        ja: "{0}駅を出発、次は {1} 駅",
        en: "Departing {0}, next stop {1}",
        zh: "从{0}出发，下一站{1}",
        zhHant: "從{0}出發，下一站{1}",
        de: "Abfahrt {0}, nächste Station {1}",
        es: "Saliendo de {0}, próxima parada {1}",
        fr: "Départ de {0}, prochain arrêt {1}",
        it: "In partenza da {0}, prossima fermata {1}",
        ptBR: "Saindo de {0}, próxima estação {1}",
        ru: "Отправление от станции {0}, следующая {1}",
        cs: "Odjezd ze stanice {0}, příští {1}",
        da: "Afgang fra {0}, næste station {1}",
        el: "Αναχώρηση από {0}, επόμενη στάση {1}",
        fi: "Lähtö asemalta {0}, seuraava asema {1}",
        id: "Berangkat dari {0}, stasiun berikutnya {1}",
        nb: "Avgang fra {0}, neste stasjon {1}",
        nl: "Vertrek uit {0}, volgende halte {1}",
        pl: "Odjazd ze stacji {0}, następna {1}",
        sv: "Avgång från {0}, nästa station {1}",
        th: "ออกจาก {0} สถานีถัดไป {1}",
        tr: "{0} istasyonundan kalkış, sonraki durak {1}",
        vi: "Rời ga {0}, ga tiếp theo {1}"
    )
    static let a11yNearCurrent = NavLoc(
        ko: "현재 {0}역 근처, 다음 {1}역",
        ja: "現在 {0} 駅付近、次は {1} 駅",
        en: "Near {0}, next {1}",
        zh: "当前在{0}附近，下一站{1}",
        zhHant: "目前在{0}附近，下一站{1}",
        de: "In der Nähe von {0}, nächste Station {1}",
        es: "Cerca de {0}, próxima parada {1}",
        fr: "Près de {0}, prochain arrêt {1}",
        it: "Vicino a {0}, prossima fermata {1}",
        ptBR: "Perto de {0}, próxima estação {1}",
        ru: "Рядом со станцией {0}, следующая {1}",
        cs: "Poblíž stanice {0}, příští {1}",
        da: "Nær {0}, næste station {1}",
        el: "Κοντά στο {0}, επόμενη στάση {1}",
        fi: "Lähellä asemaa {0}, seuraava asema {1}",
        id: "Dekat {0}, stasiun berikutnya {1}",
        nb: "Nær {0}, neste stasjon {1}",
        nl: "Bij {0}, volgende halte {1}",
        pl: "W pobliżu stacji {0}, następna {1}",
        sv: "Nära {0}, nästa station {1}",
        th: "ใกล้ {0} สถานีถัดไป {1}",
        tr: "{0} yakınında, sonraki durak {1}",
        vi: "Gần ga {0}, ga tiếp theo {1}"
    )
    static let a11yStopsToDest = NavLoc(
        ko: "{1}역까지 {0} 남음",
        ja: "{1} 駅まであと {0}",
        en: "{0} to {1}",
        zh: "距{1}还有{0}",
        zhHant: "距{1}還有{0}",
        de: "Noch {0} bis {1}",
        es: "Faltan {0} hasta {1}",
        fr: "Encore {0} jusqu'à {1}",
        it: "Ancora {0} fino a {1}",
        ptBR: "Faltam {0} até {1}",
        ru: "До станции {1}: {0}",
        cs: "Do stanice {1} zbývá {0}",
        da: "{0} til {1}",
        el: "{0} μέχρι το {1}",
        fi: "{0} asemalle {1}",
        id: "{0} lagi sampai {1}",
        nb: "{0} til {1}",
        nl: "Nog {0} tot {1}",
        pl: "Do stacji {1}: {0}",
        sv: "{0} till {1}",
        th: "อีก {0} ถึง {1}",
        tr: "{1} istasyonuna {0} kaldı",
        vi: "Còn {0} đến {1}"
    )
    static let a11yAboutMinutes = NavLoc(
        ko: "{0}, 약 {1}분",
        ja: "{0}、約 {1} 分",
        en: "{0}, about {1} min",
        zh: "{0}，约{1}分钟",
        zhHant: "{0}，約{1}分鐘",
        de: "{0}, etwa {1} Minuten",
        es: "{0}, unos {1} minutos",
        fr: "{0}, environ {1} minutes",
        it: "{0}, circa {1} minuti",
        ptBR: "{0}, cerca de {1} minutos",
        ru: "{0}, около {1} мин",
        cs: "{0}, asi {1} min",
        da: "{0}, cirka {1} minutter",
        el: "{0}, περίπου {1} λεπτά",
        fi: "{0}, noin {1} minuuttia",
        id: "{0}, sekitar {1} menit",
        nb: "{0}, omtrent {1} minutter",
        nl: "{0}, ongeveer {1} minuten",
        pl: "{0}, około {1} min",
        sv: "{0}, cirka {1} minuter",
        th: "{0} ประมาณ {1} นาที",
        tr: "{0}, yaklaşık {1} dakika",
        vi: "{0}, khoảng {1} phút"
    )
    static let toStation = NavLoc(
        ko: "{0}까지",
        ja: "{0}まで",
        en: "To {0}",
        zh: "前往{0}",
        zhHant: "前往{0}",
        de: "Bis {0}",
        es: "Hasta {0}",
        fr: "Jusqu'à {0}",
        it: "Fino a {0}",
        ptBR: "Até {0}",
        ru: "До станции {0}",
        cs: "Do stanice {0}",
        da: "Til {0}",
        el: "Προς {0}",
        fi: "Asemalle {0}",
        id: "Menuju {0}",
        nb: "Til {0}",
        nl: "Naar {0}",
        pl: "Do stacji {0}",
        sv: "Till {0}",
        th: "ไป {0}",
        tr: "{0} istasyonuna",
        vi: "Đến {0}"
    )
    static let anyDirectionWorks = NavLoc(
        ko: "어느 방향이든 가능",
        ja: "どちら方面でも可",
        en: "Any of these work",
        zh: "以下方向均可",
        zhHant: "以下方向均可",
        de: "Alle diese Züge passen",
        es: "Cualquiera de estos sirve",
        fr: "Tous ces trains conviennent",
        it: "Vanno bene tutti questi",
        ptBR: "Qualquer um destes serve",
        ru: "Подойдёт любой из них",
        cs: "Hodí se kterýkoli z nich",
        da: "Alle disse kan bruges",
        el: "Κάνει οποιοδήποτε από αυτά",
        fi: "Mikä tahansa näistä käy",
        id: "Semua ini bisa dinaiki",
        nb: "Alle disse går fint",
        nl: "Elk van deze is goed",
        pl: "Pasuje każdy z nich",
        sv: "Alla dessa fungerar",
        th: "ขึ้นขบวนไหนก็ได้",
        tr: "Bunların hepsi olur",
        vi: "Tàu nào dưới đây cũng được"
    )
    static let trainBoundFor = NavLoc(
        ko: "{0}행",
        ja: "{0}行き",
        en: "To {0}",
        zh: "开往{0}",
        zhHant: "開往{0}",
        de: "Nach {0}",
        es: "A {0}",
        fr: "Vers {0}",
        it: "Per {0}",
        ptBR: "Sentido {0}",
        ru: "До {0}",
        cs: "Do {0}",
        da: "Mod {0}",
        el: "Προς {0}",
        fi: "Määränpää {0}",
        id: "Tujuan {0}",
        nb: "Mot {0}",
        nl: "Naar {0}",
        pl: "Do {0}",
        sv: "Mot {0}",
        th: "ไป {0}",
        tr: "{0} yönü",
        vi: "Đi {0}"
    )
    static let landmarksDirection = NavLoc(
        ko: "{0} 방향",
        ja: "{0} 方面",
        en: "{0} direction",
        zh: "{0} 方向",
        zhHant: "{0} 方向",
        de: "Richtung {0}",
        es: "Dirección {0}",
        fr: "Direction {0}",
        it: "Direzione {0}",
        ptBR: "Sentido {0}",
        ru: "В сторону {0}",
        cs: "Směr {0}",
        da: "Retning {0}",
        el: "Κατεύθυνση {0}",
        fi: "Suunta {0}",
        id: "Arah {0}",
        nb: "Retning {0}",
        nl: "Richting {0}",
        pl: "Kierunek {0}",
        sv: "Riktning {0}",
        th: "ทาง {0}",
        tr: "{0} yönü",
        vi: "Hướng {0}"
    )
    static let towardDestination = NavLoc(
        ko: "{0} 방면",
        ja: "{0}方面",
        en: "Toward {0}",
        zh: "开往{0}方向",
        zhHant: "開往{0}方向",
        de: "Richtung {0}",
        es: "Dirección {0}",
        fr: "Direction {0}",
        it: "Direzione {0}",
        ptBR: "Sentido {0}",
        ru: "В сторону {0}",
        cs: "Směr {0}",
        da: "Retning {0}",
        el: "Κατεύθυνση {0}",
        fi: "Suunta {0}",
        id: "Arah {0}",
        nb: "Retning {0}",
        nl: "Richting {0}",
        pl: "Kierunek {0}",
        sv: "Riktning {0}",
        th: "ทาง {0}",
        tr: "{0} yönü",
        vi: "Hướng {0}"
    )
    static let innerLoop = NavLoc(
        ko: "내선순환",
        ja: "内回り",
        en: "Inner Loop",
        zh: "内环方向",
        zhHant: "內環方向",
        de: "Innenring",
        es: "Circuito interior",
        fr: "Boucle intérieure",
        it: "Anello interno",
        ptBR: "Circuito interno",
        ru: "Внутреннее кольцо",
        cs: "Vnitřní okruh",
        da: "Indre ring",
        el: "Εσωτερικός κύκλος",
        fi: "Sisäkehä",
        id: "Lingkar dalam",
        nb: "Indre ring",
        nl: "Binnenring",
        pl: "Pętla wewnętrzna",
        sv: "Inre ringen",
        th: "วงใน",
        tr: "İç halka",
        vi: "Vòng trong"
    )
    static let outerLoop = NavLoc(
        ko: "외선순환",
        ja: "外回り",
        en: "Outer Loop",
        zh: "外环方向",
        zhHant: "外環方向",
        de: "Außenring",
        es: "Circuito exterior",
        fr: "Boucle extérieure",
        it: "Anello esterno",
        ptBR: "Circuito externo",
        ru: "Внешнее кольцо",
        cs: "Vnější okruh",
        da: "Ydre ring",
        el: "Εξωτερικός κύκλος",
        fi: "Ulkokehä",
        id: "Lingkar luar",
        nb: "Ytre ring",
        nl: "Buitenring",
        pl: "Pętla zewnętrzna",
        sv: "Yttre ringen",
        th: "วงนอก",
        tr: "Dış halka",
        vi: "Vòng ngoài"
    )
    static let towardTerminus = NavLoc(
        ko: "{0}행",
        ja: "{0}行き",
        en: "Toward {0}",
        zh: "开往{0}",
        zhHant: "開往{0}",
        de: "Richtung {0}",
        es: "Dirección {0}",
        fr: "Direction {0}",
        it: "Direzione {0}",
        ptBR: "Sentido {0}",
        ru: "В сторону {0}",
        cs: "Směr {0}",
        da: "Retning {0}",
        el: "Κατεύθυνση {0}",
        fi: "Suunta {0}",
        id: "Arah {0}",
        nb: "Retning {0}",
        nl: "Richting {0}",
        pl: "Kierunek {0}",
        sv: "Riktning {0}",
        th: "ทาง {0}",
        tr: "{0} yönü",
        vi: "Hướng {0}"
    )
    static let currentStationA11y = NavLoc(
        ko: "{0}역{1}. 현재역 변경하려면 탭하세요.",
        ja: "{0}駅{1}。タップで現在の駅を変更。",
        en: "{0} Station{1}. Tap to change the current station.",
        zh: "{0}站{1}。点按更改当前车站。",
        zhHant: "{0}站{1}。點選更改目前車站。",
        de: "Station {0}{1}. Tippen, um die aktuelle Station zu ändern.",
        es: "Estación {0}{1}. Toca para cambiar la estación actual.",
        fr: "Station {0}{1}. Touchez pour changer la station actuelle.",
        it: "Stazione {0}{1}. Tocca per cambiare la stazione attuale.",
        ptBR: "Estação {0}{1}. Toque para mudar a estação atual.",
        ru: "Станция {0}{1}. Коснитесь, чтобы сменить текущую станцию.",
        cs: "Stanice {0}{1}. Klepnutím změníte aktuální stanici.",
        da: "{0} station{1}. Tryk for at skifte nuværende station.",
        el: "Σταθμός {0}{1}. Πατήστε για αλλαγή τρέχοντος σταθμού.",
        fi: "Asema {0}{1}. Vaihda nykyinen asema napauttamalla.",
        id: "Stasiun {0}{1}. Ketuk untuk mengganti stasiun saat ini.",
        nb: "{0} stasjon{1}. Trykk for å bytte nåværende stasjon.",
        nl: "Station {0}{1}. Tik om het huidige station te wijzigen.",
        pl: "Stacja {0}{1}. Stuknij, by zmienić bieżącą stację.",
        sv: "Station {0}{1}. Tryck för att byta nuvarande station.",
        th: "สถานี {0}{1} แตะเพื่อเปลี่ยนสถานีปัจจุบัน",
        tr: "{0} istasyonu{1}. Bulunduğun istasyonu değiştirmek için dokun.",
        vi: "Ga {0}{1}. Chạm để đổi ga hiện tại."
    )
    static let departurePlaceholder = NavLoc(
        ko: "어디서 출발하시나요?",
        ja: "どこから出発しますか？",
        en: "Where are you departing from?",
        zh: "从哪里出发？",
        zhHant: "從哪裡出發？",
        de: "Wo fährst du los?",
        es: "¿Desde dónde sales?",
        fr: "D'où partez-vous ?",
        it: "Da dove parti?",
        ptBR: "De onde você vai sair?",
        ru: "Откуда вы едете?",
        cs: "Odkud vyrážíte?",
        da: "Hvor rejser du fra?",
        el: "Από πού ξεκινάτε;",
        fi: "Mistä lähdet?",
        id: "Berangkat dari mana?",
        nb: "Hvor reiser du fra?",
        nl: "Waar vertrek je?",
        pl: "Skąd ruszasz?",
        sv: "Var reser du från?",
        th: "ออกเดินทางจากไหน?",
        tr: "Nereden yola çıkıyorsun?",
        vi: "Bạn xuất phát từ đâu?"
    )
    static let departureHint = NavLoc(
        ko: "탭 해서 출발지를 정해주세요",
        ja: "タップして出発地を選んでください",
        en: "Tap to set your departure",
        zh: "点击设定出发地",
        zhHant: "點選設定出發地",
        de: "Tippen, um den Start festzulegen",
        es: "Toca para elegir el origen",
        fr: "Touchez pour choisir le départ",
        it: "Tocca per scegliere la partenza",
        ptBR: "Toque para definir a origem",
        ru: "Коснитесь, чтобы выбрать старт",
        cs: "Klepnutím zvolte start",
        da: "Tryk for at vælge start",
        el: "Πατήστε για να ορίσετε αφετηρία",
        fi: "Valitse lähtöpaikka napauttamalla",
        id: "Ketuk untuk memilih asal",
        nb: "Trykk for å velge start",
        nl: "Tik om je vertrekpunt te kiezen",
        pl: "Stuknij, by wybrać start",
        sv: "Tryck för att välja start",
        th: "แตะเพื่อเลือกต้นทาง",
        tr: "Başlangıç noktası seçmek için dokun",
        vi: "Chạm để chọn điểm xuất phát"
    )
    static let locating = NavLoc(
        ko: "현재 위치 확인 중...",
        ja: "現在地を確認中...",
        en: "Detecting location...",
        zh: "正在定位...",
        zhHant: "正在定位...",
        de: "Standort wird ermittelt …",
        es: "Obteniendo ubicación…",
        fr: "Localisation en cours…",
        it: "Rilevamento posizione…",
        ptBR: "Obtendo localização…",
        ru: "Определяем местоположение…",
        cs: "Zjišťuji polohu…",
        da: "Finder din lokalitet…",
        el: "Εντοπισμός τοποθεσίας…",
        fi: "Haetaan sijaintia…",
        id: "Mencari lokasi…",
        nb: "Finner posisjonen din…",
        nl: "Locatie bepalen…",
        pl: "Ustalanie lokalizacji…",
        sv: "Hämtar din plats…",
        th: "กำลังหาตำแหน่ง…",
        tr: "Konum bulunuyor…",
        vi: "Đang xác định vị trí…"
    )
    static let preBoardingStatus = NavLoc(
        ko: "탑승 전",
        ja: "乗車前",
        en: "Before boarding",
        zh: "乘车前",
        zhHant: "搭車前",
        de: "Vor dem Einsteigen",
        es: "Antes de subir",
        fr: "Avant de monter",
        it: "Prima di salire",
        ptBR: "Antes de embarcar",
        ru: "До посадки",
        cs: "Před nástupem",
        da: "Før påstigning",
        el: "Πριν την επιβίβαση",
        fi: "Ennen nousua",
        id: "Sebelum naik",
        nb: "Før påstigning",
        nl: "Voor instappen",
        pl: "Przed wejściem",
        sv: "Före påstigning",
        th: "ก่อนขึ้นรถ",
        tr: "Binmeden önce",
        vi: "Trước khi lên tàu"
    )
    static let boardedStatus = NavLoc(
        ko: "탑승 중",
        ja: "乗車中",
        en: "On board",
        zh: "乘车中",
        zhHant: "搭車中",
        de: "Im Zug",
        es: "A bordo",
        fr: "À bord",
        it: "A bordo",
        ptBR: "A bordo",
        ru: "В поезде",
        cs: "Ve vlaku",
        da: "Om bord",
        el: "Εν κινήσει",
        fi: "Kyydissä",
        id: "Di dalam kereta",
        nb: "Om bord",
        nl: "Onderweg",
        pl: "W pociągu",
        sv: "Ombord",
        th: "อยู่บนรถ",
        tr: "Trende",
        vi: "Đang trên tàu"
    )
    static let slideToBoard = NavLoc(
        ko: "밀어서 탑승하기",
        ja: "スワイプで乗車",
        en: "Slide to board",
        zh: "滑动上车",
        zhHant: "滑動上車",
        de: "Zum Einsteigen schieben",
        es: "Desliza para subir",
        fr: "Glisser pour monter",
        it: "Scorri per salire",
        ptBR: "Deslize para embarcar",
        ru: "Сдвиньте — я в поезде",
        cs: "Posunutím nastoupit",
        da: "Skub for at stige på",
        el: "Σύρετε για επιβίβαση",
        fi: "Liu'uta noustaksesi",
        id: "Geser untuk naik",
        nb: "Skyv for å gå på",
        nl: "Schuif om in te stappen",
        pl: "Przesuń, by wsiąść",
        sv: "Dra för att kliva på",
        th: "เลื่อนเพื่อขึ้นรถ",
        tr: "Binmek için kaydır",
        vi: "Trượt để lên tàu"
    )
    static let slideToTransfer = NavLoc(
        ko: "밀어서 환승하기",
        ja: "スワイプで乗換",
        en: "Slide to transfer",
        zh: "滑动换乘",
        zhHant: "滑動轉乘",
        de: "Zum Umsteigen schieben",
        es: "Desliza para transbordar",
        fr: "Glisser pour changer",
        it: "Scorri per cambiare",
        ptBR: "Deslize para baldear",
        ru: "Сдвиньте для пересадки",
        cs: "Posunutím přestoupit",
        da: "Skub for at skifte",
        el: "Σύρετε για μετεπιβίβαση",
        fi: "Liu'uta vaihtaaksesi",
        id: "Geser untuk transit",
        nb: "Skyv for å bytte",
        nl: "Schuif om over te stappen",
        pl: "Przesuń, by się przesiąść",
        sv: "Dra för att byta",
        th: "เลื่อนเพื่อต่อรถ",
        tr: "Aktarma için kaydır",
        vi: "Trượt để chuyển tuyến"
    )
    static let slideToAlight = NavLoc(
        ko: "밀어서 내리기",
        ja: "スワイプで下車",
        en: "Slide to alight",
        zh: "滑动下车",
        zhHant: "滑動下車",
        de: "Zum Aussteigen schieben",
        es: "Desliza para bajar",
        fr: "Glisser pour descendre",
        it: "Scorri per scendere",
        ptBR: "Deslize para descer",
        ru: "Сдвиньте — я вышел",
        cs: "Posunutím vystoupit",
        da: "Skub for at stå af",
        el: "Σύρετε για αποβίβαση",
        fi: "Liu'uta jäädäksesi pois",
        id: "Geser untuk turun",
        nb: "Skyv for å gå av",
        nl: "Schuif om uit te stappen",
        pl: "Przesuń, by wysiąść",
        sv: "Dra för att kliva av",
        th: "เลื่อนเพื่อลงรถ",
        tr: "İnmek için kaydır",
        vi: "Trượt để xuống tàu"
    )
    static let revisitAlertTitle = NavLoc(
        ko: "이미 지나간 단계예요",
        ja: "完了済みのステップです",
        en: "Already completed",
        zh: "已完成的步骤",
        zhHant: "已完成的步驟",
        de: "Schon erledigt",
        es: "Paso completado",
        fr: "Étape déjà terminée",
        it: "Passaggio già completato",
        ptBR: "Etapa já concluída",
        ru: "Этот шаг пройден",
        cs: "Krok už je hotový",
        da: "Allerede gennemført",
        el: "Ολοκληρωμένο βήμα",
        fi: "Vaihe on jo tehty",
        id: "Langkah sudah selesai",
        nb: "Allerede fullført",
        nl: "Al voltooid",
        pl: "Ten krok jest już za tobą",
        sv: "Redan klart",
        th: "ขั้นตอนนี้ผ่านไปแล้ว",
        tr: "Bu adım tamamlandı",
        vi: "Bước này đã xong"
    )
    static let revisitAlertMessage = NavLoc(
        ko: "이미 완료한 단계입니다. 다시 보시겠습니까?",
        ja: "完了済みのステップです。戻りますか？",
        en: "This step is already done. Do you want to go back to review it?",
        zh: "此步骤已完成，要返回查看吗？",
        zhHant: "此步驟已完成，要返回查看嗎？",
        de: "Diesen Schritt hast du schon abgeschlossen. Möchtest du ihn noch einmal ansehen?",
        es: "Ya completaste este paso. ¿Quieres volver a verlo?",
        fr: "Cette étape est déjà terminée. Voulez-vous revenir la consulter ?",
        it: "Hai già completato questo passaggio. Vuoi tornare a rivederlo?",
        ptBR: "Você já concluiu esta etapa. Quer voltar para revê-la?",
        ru: "Вы уже прошли этот шаг. Вернуться и посмотреть ещё раз?",
        cs: "Tento krok už máte za sebou. Chcete se k němu vrátit?",
        da: "Du har allerede gennemført dette trin. Vil du gå tilbage og se det igen?",
        el: "Αυτό το βήμα έχει ήδη ολοκληρωθεί. Θέλετε να επιστρέψετε σε αυτό;",
        fi: "Tämä vaihe on jo tehty. Haluatko palata katsomaan sitä?",
        id: "Langkah ini sudah selesai. Mau kembali untuk melihatnya?",
        nb: "Dette trinnet er allerede fullført. Vil du gå tilbake og se på det?",
        nl: "Deze stap heb je al voltooid. Wil je teruggaan om hem te bekijken?",
        pl: "Ten krok został już ukończony. Chcesz do niego wrócić?",
        sv: "Det här steget är redan klart. Vill du gå tillbaka och titta igen?",
        th: "ขั้นตอนนี้เสร็จแล้ว ต้องการย้อนกลับไปดูไหม?",
        tr: "Bu adımı zaten tamamladın. Tekrar bakmak için geri dönmek ister misin?",
        vi: "Bạn đã hoàn thành bước này. Bạn có muốn quay lại xem không?"
    )
    static let revisitContinue = NavLoc(
        ko: "계속 진행",
        ja: "続ける",
        en: "Continue",
        zh: "继续",
        zhHant: "繼續",
        de: "Weiter",
        es: "Continuar",
        fr: "Continuer",
        it: "Continua",
        ptBR: "Continuar",
        ru: "Продолжить",
        cs: "Pokračovat",
        da: "Fortsæt",
        el: "Συνέχεια",
        fi: "Jatka",
        id: "Lanjutkan",
        nb: "Fortsett",
        nl: "Doorgaan",
        pl: "Dalej",
        sv: "Fortsätt",
        th: "ไปต่อ",
        tr: "Devam et",
        vi: "Tiếp tục"
    )
    static let revisitGoBack = NavLoc(
        ko: "돌아가서 보기",
        ja: "戻って確認",
        en: "Go back",
        zh: "返回查看",
        zhHant: "返回查看",
        de: "Zurück",
        es: "Volver",
        fr: "Revenir",
        it: "Torna indietro",
        ptBR: "Voltar",
        ru: "Вернуться",
        cs: "Vrátit se",
        da: "Gå tilbage",
        el: "Επιστροφή",
        fi: "Palaa",
        id: "Kembali",
        nb: "Gå tilbake",
        nl: "Teruggaan",
        pl: "Wróć",
        sv: "Gå tillbaka",
        th: "ย้อนกลับไปดู",
        tr: "Geri dön",
        vi: "Quay lại xem"
    )
    static let transferLabel = NavLoc(
        ko: "환승",
        ja: "乗換",
        en: "Transfer",
        zh: "换乘",
        zhHant: "轉乘",
        de: "Umstieg",
        es: "Transbordo",
        fr: "Correspondance",
        it: "Cambio",
        ptBR: "Baldeação",
        ru: "Пересадка",
        cs: "Přestup",
        da: "Skift",
        el: "Μετεπιβίβαση",
        fi: "Vaihto",
        id: "Transit",
        nb: "Bytte",
        nl: "Overstap",
        pl: "Przesiadka",
        sv: "Byte",
        th: "ต่อรถ",
        tr: "Aktarma",
        vi: "Chuyển tuyến"
    )
    static let departureLabel = NavLoc(
        ko: "출발",
        ja: "出発",
        en: "From",
        zh: "出发",
        zhHant: "出發",
        de: "Start",
        es: "Origen",
        fr: "Départ",
        it: "Partenza",
        ptBR: "Origem",
        ru: "Откуда",
        cs: "Odkud",
        da: "Fra",
        el: "Από",
        fi: "Mistä",
        id: "Asal",
        nb: "Fra",
        nl: "Van",
        pl: "Start",
        sv: "Från",
        th: "ต้นทาง",
        tr: "Nereden",
        vi: "Từ"
    )
    static let arrivalLabel = NavLoc(
        ko: "도착",
        ja: "到着",
        en: "To",
        zh: "到达",
        zhHant: "到達",
        de: "Ziel",
        es: "Destino",
        fr: "Arrivée",
        it: "Arrivo",
        ptBR: "Destino",
        ru: "Куда",
        cs: "Kam",
        da: "Til",
        el: "Προς",
        fi: "Minne",
        id: "Tujuan",
        nb: "Til",
        nl: "Naar",
        pl: "Cel",
        sv: "Till",
        th: "ปลายทาง",
        tr: "Nereye",
        vi: "Đến"
    )
    static let noTransfer = NavLoc(
        ko: "환승 없음",
        ja: "乗換なし",
        en: "No transfer",
        zh: "无换乘",
        zhHant: "無轉乘",
        de: "Ohne Umstieg",
        es: "Sin transbordo",
        fr: "Sans correspondance",
        it: "Senza cambi",
        ptBR: "Sem baldeação",
        ru: "Без пересадок",
        cs: "Bez přestupu",
        da: "Ingen skift",
        el: "Χωρίς μετεπιβίβαση",
        fi: "Ei vaihtoja",
        id: "Tanpa transit",
        nb: "Ingen bytter",
        nl: "Geen overstap",
        pl: "Bez przesiadek",
        sv: "Inget byte",
        th: "ไม่ต้องต่อรถ",
        tr: "Aktarmasız",
        vi: "Không chuyển tuyến"
    )
    static let startJourney = NavLoc(
        ko: "출발하기",
        ja: "出発する",
        en: "Start Journey",
        zh: "开始导航",
        zhHant: "開始導航",
        de: "Los geht's",
        es: "Empezar viaje",
        fr: "C'est parti",
        it: "Inizia il viaggio",
        ptBR: "Começar trajeto",
        ru: "Поехали",
        cs: "Vyrazit",
        da: "Start turen",
        el: "Ξεκινάμε",
        fi: "Aloita matka",
        id: "Mulai perjalanan",
        nb: "Start reisen",
        nl: "Start reis",
        pl: "Ruszamy",
        sv: "Starta resan",
        th: "เริ่มเดินทาง",
        tr: "Yolculuğa başla",
        vi: "Bắt đầu đi"
    )
    static let changeDestination = NavLoc(
        ko: "목적지 다시 선택",
        ja: "目的地を変更",
        en: "Change destination",
        zh: "重新选择目的地",
        zhHant: "重新選擇目的地",
        de: "Ziel ändern",
        es: "Cambiar destino",
        fr: "Changer de destination",
        it: "Cambia destinazione",
        ptBR: "Mudar destino",
        ru: "Сменить пункт назначения",
        cs: "Změnit cíl",
        da: "Skift destination",
        el: "Αλλαγή προορισμού",
        fi: "Vaihda määränpää",
        id: "Ganti tujuan",
        nb: "Bytt reisemål",
        nl: "Bestemming wijzigen",
        pl: "Zmień cel",
        sv: "Byt resmål",
        th: "เปลี่ยนปลายทาง",
        tr: "Varış noktasını değiştir",
        vi: "Đổi điểm đến"
    )
}
